name       : unibilium
version    : 1.2.1
release    : 2
source     :
    - https://github.com/mauke/unibilium/archive/v1.2.1.tar.gz : 6045b4f6adca7b1123284007675ca71f718f70942d3a93d8b9fa5bd442006ec1
license    : LGPL-3.0
component  : programming
summary    : A terminfo parsing library
description: |
    Unibilium is a very basic terminfo library. It can read and write ncurses-style terminfo files. It doesn't depend on curses or any other library. It also doesn't use global variables, so it should be thread-safe.
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
check      : |
    %make test
