name       : unibilium
version    : 1.2.0
release    : 1
source     :
    - https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz : 623af1099515e673abfd3cae5f2fa808a09ca55dda1c65a7b5c9424eb304ead8
license    : LGPL3
summary    : A terminfo parsing library
description: |
    A terminfo parsing library 
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
