name       : unibilium
version    : 2.0.0
release    : 3
source     :
    - https://github.com/mauke/unibilium/archive/v2.0.0.tar.gz : 78997d38d4c8177c60d3d0c1aa8c53fd0806eb21825b7b335b1768d7116bc1c1
license    : LGPL-3.0
component  : programming
summary    : A terminfo parsing library
description: |
    Unibilium is a very basic terminfo library. It can read and write ncurses-style terminfo files. It doesn't depend on curses or any other library. It also doesn't use global variables, so it should be thread-safe.
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
check      : |
    %make test
